In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
scalar = torch.tensor(7)
scalar.ndim

0

In [ ]:
scalar.dim()

0

#### Random Tensors

In [ ]:
rTensor = torch.rand(3, 4)
rTensor[0][0].dtype

torch.float32

In [ ]:
# Create random tensor with similar shape to an mage tensor
rIST = torch.rand(size=(3, 224, 224)) # height, width, color channels
rIST.shape, rIST.ndim

(torch.Size([3, 224, 224]), 3)

Creating a range of tensors and tensors-like

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(start=5, end=14, step=3)

tensor([ 5,  8, 11])

In [ ]:
# creating tensors like
zer = torch.zeros_like(input=torch.arange(0, 10))
zer
torch.ones_like(input=torch.arange(0, 10))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Tensor Datatypes


In [ ]:
#float 32 tensor
f32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
f32_tensor

tensor([3., 6., 9.])

In [ ]:
# pytorch tensors have a default datatype of torch.float32
f32_tensor.dtype

torch.float32

In [ ]:
f32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32, # what data type is the tensor
                          device=None, # What device is t
                          requires_grad=False)

In [ ]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = torch.tensor([2.0, 3.0, 1.0], dtype=torch.int32)
t3 = t1 * t2
t3

tensor([2., 6., 3.])

In [ ]:
### Getting information from tensors
some_tensor = torch.rand(size=(3,4))
print(some_tensor)
print(f"datatype: {some_tensor.dtype} \nshape: {some_tensor.shape} \ndevice: {some_tensor.device}")

tensor([[0.1812, 0.8938, 0.6281, 0.3859],
        [0.3979, 0.7519, 0.0452, 0.2633],
        [0.7193, 0.2211, 0.7605, 0.3653]])
datatype: torch.float32 
shape: torch.Size([3, 4]) 
device: cpu


In [ ]:
my_tensor = torch.rand((2,2,2), dtype=torch.float16, device=None)
print(f"my_tensor: {my_tensor} \n")
print(f"datatype: {my_tensor.dtype} \nshape: {my_tensor.shape} \ndevice: {my_tensor.device}")

my_tensor: tensor([[[0.6445, 0.7783],
         [0.1719, 0.3086]],

        [[0.0273, 0.1978],
         [0.0093, 0.5278]]], dtype=torch.float16) 

datatype: torch.float16 
shape: torch.Size([2, 2, 2]) 
device: cpu


### Manipulating Tensors (Tensor operations)
- addition, subtraction, multiplication, division, matrix multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor += 10
tensor

tensor([11, 12, 13])

In [ ]:
tensor *= 10
tensor

tensor([110, 120, 130])

In [ ]:
tensor -= 10
tensor

tensor([100, 110, 120])

In [ ]:
tensor = torch.div(tensor, 10)
tensor

tensor([10., 11., 12.])

In [ ]:
## matrix multiplication
idMatrix = torch.tensor([[1,0,0],[0,1,0],[0,0,1]], dtype=torch.float32)
A = torch.rand((3,3))

In [ ]:
A

tensor([[0.4059, 0.0396, 0.0136],
        [0.0639, 0.6109, 0.0115],
        [0.9705, 0.7902, 0.8219]])

In [ ]:
idMatrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
%%time
torch.matmul(A, idMatrix)

CPU times: user 219 µs, sys: 31 µs, total: 250 µs
Wall time: 260 µs


tensor([[0.4059, 0.0396, 0.0136],
        [0.0639, 0.6109, 0.0115],
        [0.9705, 0.7902, 0.8219]])

In [ ]:
torch.rand((3,2)).T

tensor([[0.4639, 0.9489, 0.2463],
        [0.0510, 0.9375, 0.7953]])

### Tensor Agregation
finding min, max, mean, sum, etc.

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # needs torch.float32

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping - reshapes an input tensor
* View - return a view of an imput tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
x = torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(2,5) # has to have same number of elements as input tensor!
x_reshaped,x_reshaped.size()

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# Change the view
z = x.view(1,10)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Changing z changes x as a view of a tensor shares the same memory as the original input
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked1 = torch.stack([x,x,x,x], dim=1)
x_stacked,x_stacked1

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]))

In [ ]:
# torch.squeeze() removes all dimensions with size `1`...think of this as "simplifying" a tensor down to the least dimensions needed
x=torch.rand(3,1,3)
y=torch.squeeze(x)
print(f"x = {x}\nx.shape = {x.shape}\n")
print(f"y = {y}\ny.shape = {y.shape}\n")

x = tensor([[[0.4463, 0.1365, 0.0429]],

        [[0.6311, 0.4949, 0.7231]],

        [[0.2918, 0.6910, 0.9703]]])
x.shape = torch.Size([3, 1, 3])

y = tensor([[0.4463, 0.1365, 0.0429],
        [0.6311, 0.4949, 0.7231],
        [0.2918, 0.6910, 0.9703]])
y.shape = torch.Size([3, 3])



In [ ]:
# torch.unsqueeze() adds a single dimension to a tensor at a specific dimension
z=torch.unsqueeze(y,1)
print(f"y = {y}\ny.shape = {y.shape}\n")
print(f"z = {z}\nz.shape = {z.shape}")

y = tensor([[0.7802, 0.2094, 0.6166],
        [0.6140, 0.4900, 0.4759],
        [0.1873, 0.3079, 0.2077]])
y.shape = torch.Size([3, 3])

z = tensor([[[0.7802, 0.2094, 0.6166]],

        [[0.6140, 0.4900, 0.4759]],

        [[0.1873, 0.3079, 0.2077]]])
z.shape = torch.Size([3, 1, 3])


In [ ]:
# torch.permute() rearranges the dimensions of a target tensor in a specified order
a=torch.rand((1,2,3))
b=torch.permute(a,(2,0,1))
print(f"{a}{a.shape}")
print(f"{b}{b.shape}")

tensor([[[0.2348, 0.7659, 0.1842],
         [0.2833, 0.8096, 0.5380]]])torch.Size([1, 2, 3])
tensor([[[0.2348, 0.2833]],

        [[0.7659, 0.8096]],

        [[0.1842, 0.5380]]])torch.Size([3, 1, 2])


## Indexing

In [1]:
import torch

In [3]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
x[0,0]

tensor([1, 2, 3])

In [8]:
x[0,2,2]

tensor(9)

In [9]:
# You can use `:` to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [10]:
x[:,:,1]

tensor([[2, 5, 8]])

In [12]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [14]:
x[0,0,:]

tensor([1, 2, 3])

In [15]:
x[0,:,2]

tensor([3, 6, 9])

## PyTorch and NumPy

In [29]:
# np array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor # np's default datatype is float64, which is why the data in `tensor` is float64

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [32]:
# tensor to np array
tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor,np_tensor # torch's default datatype is float32, hence the data is float32

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility - Trying to take the random out of random (random seeds)

In [33]:
a=torch.rand(3,4)
b=torch.rand(3,4)
a,b

(tensor([[0.1921, 0.1011, 0.8220, 0.3285],
         [0.5719, 0.7962, 0.8264, 0.0758],
         [0.0857, 0.7383, 0.6417, 0.4530]]),
 tensor([[0.0630, 0.9882, 0.7917, 0.5283],
         [0.6847, 0.4227, 0.7292, 0.1084],
         [0.9927, 0.1663, 0.2782, 0.0972]]))

In [34]:
a==b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [38]:
import torch
RANDOM_SEED=69
torch.manual_seed(RANDOM_SEED)

In [44]:
torch.manual_seed(RANDOM_SEED) # `torch.manual_seed() usually only works for a method
c=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
d=torch.rand(3,4)
c,d,c==d

(tensor([[0.8398, 0.8042, 0.1213, 0.5309],
         [0.6646, 0.4077, 0.0888, 0.2429],
         [0.7053, 0.6216, 0.9188, 0.0185]]),
 tensor([[0.8398, 0.8042, 0.1213, 0.5309],
         [0.6646, 0.4077, 0.0888, 0.2429],
         [0.7053, 0.6216, 0.9188, 0.0185]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

### Getting a GPU
* Use Google Colab
* Use own GPU
* Use cloud computing (GCP, AWS, Azure)

For bottom two options, PyTorch + GPU (cuda) takes a bit of setup...so research! :)

### Check for GPU access with PyTorch



In [4]:
import torch
torch.cuda.is_available()

True

In [5]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors and models on the GPU

In [7]:
import torch

In [8]:
# by default, tensor is on cpu
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
# move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

## Moving tensors back to cpu

In [15]:
# if tensor is on GPU, cannot transport it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [17]:
tensor_on_gpu=tensor_on_gpu.to("cpu")

In [19]:
tensor_on_gpu.numpy()

array([1, 2, 3])

## Section 00 Exercises

In [32]:
torch.cuda.manual_seed(0)
t2=torch.rand((7,7))
t2

tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

In [33]:
torch.cuda.manual_seed(0)
t3=torch.rand((1,7))
t3

tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]])

In [34]:
torch.matmul(t2,t3.T)

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

In [35]:
torch.cuda.is_available()

True

In [37]:
torch.manual_seed(1234)
a=torch.rand((2,3))
torch.manual_seed(1234)
b=torch.rand((2,3))
a=a.to('cuda')
b=b.to('cuda')
a.device,b.device

(device(type='cuda', index=0), device(type='cuda', index=0))

In [39]:
c=torch.matmul(a,b.T)

In [40]:
c.min(),c.max()

(tensor(0.2161, device='cuda:0'), tensor(0.6287, device='cuda:0'))

In [45]:
torch.manual_seed(7)
penis=torch.rand(1,1,1,10)
penischild=torch.squeeze(penis)
print(f"penis' shape: {penis.shape}\npenischild's shape: {penischild.shape}")

penis' shape: torch.Size([1, 1, 1, 10])
penischild's shape: torch.Size([10])
